version: '3.7'

services:
  mysql:
    container_name: musicas-mysql-loopback
    image: musicas-mysql-loopback
    build:
      context: .
      dockerfile: ./dockerfile.mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    networks:
      - musicas-network
    ports:
      - 3308:3308
  app:
    depends_on:
      - mysql
    container_name: loopback-mysql
    image: loopback-mysql
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3308:3308
    networks:
      - musicas-network

networks:
  musicas-network:
